### ISSUE TITLE
please help me build my even/odd strategy on binarybot

### ISSUE THREAD

**Issue by Aloyjoe** [binary-ex-machina/binary.com-bot#11]
help me admin to write this strategy in binarybot with martingale
1.EVEN
2.EVEN
3.ODD
4.ODD
5.EVEN
6.EVEN
7.EVEN
8.ODD
9.ODD
10.ODD
11.EVEN
12.EVEN
13.EVEN
14.EVEN
15.ODD
16.ODD
17.ODD
18.ODD
19. Return as 1....
add martingale thanks

**Comment by binary-ex-machina** [comment]
You can change the sequence on the variable, just using the initial letter: e=even and o=odd

![image](https://user-images.githubusercontent.com/34610787/36746578-70ae9b28-1bd1-11e8-9972-4410e9ce4e77.png)

[evenodd-martingale.xml.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1764173/evenodd-martingale.xml.zip)

**Comment by Aloyjoe** [comment]
Thanks for all your help
