### ISSUE TITLE
How to load indicators and PSAR indicator.

### ISSUE THREAD

**Issue by xremmy** [binary-ex-machina/binary.com-bot#12]
Good Day Friend, 
Please i want to know how load your indicators onto the bot page, i tried loading them like the other scripts but nothing comes up either in the functions tab or indicators tab. 

Also, can you help develop a a Parabolic SAR indicator. I am using it manually to trade goes out , and it looks promising.
The strategy is , when a Parabolic SAR dot appears at the end of a 1 minute candle, trade is placed for 3 minutes and barrier is set to give a payout of 200%. Present barrier for vol 100 is set at +14.5, -14.5. 
Thank you.

**Comment by binary-ex-machina** [comment]
Parabolic SAR is very hard to create on binary.com
You saying that NONe of the indicators of my repository are loading, or there is one that you can't load?
