### ISSUE TITLE
Martingale after a Win

### ISSUE THREAD

**Issue by Agentsbu** [binary-ex-machina/binary.com-bot#14]
Hi Machina, i'm trying to create a botg that apply martingale after a win just like Oscars martingale, but the problem is that oscars martingale does not martingale if you lose One Time. I need a bot that martingale after a win even if it loss 1 time.
![binary bot](https://user-images.githubusercontent.com/26632197/37223324-fd6438a6-2384-11e8-9dca-44e6139eb7b8.png)

**Comment by binary-ex-machina** [comment]
Oscar's Grind and Martingale are two different strategies, that mainly cancel each other. Oscar grind increase your stake one time (0.35 > 0.7) when you win and stay the same of loose. Martingale apply like Oscar's grind and when lose, it backs to the initial stake.
