### ISSUE TITLE
count last digit

### ISSUE THREAD

**Issue by vajromchendroz** [binary-ex-machina/binary.com-bot#15]
pls help me, i want to analyze last digit. ex :  if last digit = 0 start count 5 tick, if result not 0 then signal as 1 ( i mean we only count when last digit = 0 ), so if signal > 10 than start buy Digit match. big thanks

**Comment by binary-ex-machina** [comment]
when you write signal, from what?

**Comment by vajromchendroz** [comment]
i figure signal as start LD=0, then count 5 tick if the result not LD 0 so mark as signal 1, then wait another LD=0 count 5 tick again if result not LD 0 mark as signal 2 etc. if i have signal > 10 i start purchase digitmatch on every LD = 0, if lose marty with 10% of the stake :)

**Comment by binary-ex-machina** [comment]
sorry, can't created it for waiting ticks like that.

**Comment by vajromchendroz** [comment]
yeah, i've tried when start count before 5 tick if LD 0 appears then its start recalculate again tq
