### ISSUE TITLE
labouchere

### ISSUE THREAD

**Issue by armmar4711** [binary-ex-machina/binary.com-bot#16]
can you set your labouchere to trade again(set all to first start)  if l they get target profit 
ex target profit = 1 list  0.2 0.2 0.2 0.2 0.2 if it get profit set it to target profit = 1 list  0.2 0.2 0.2 0.2 0.2 again

**Comment by binary-ex-machina** [comment]
that's against the strategy. The idea is to end the list and then you make another. It's about control.
