### ISSUE TITLE
input balance start and balance after

### ISSUE THREAD

**Issue by vajromchendroz** [binary-ex-machina/binary.com-bot#17]
please help me to input block 4, if balance after - balance start > 20 bot stop, if balance after - balance start < -20 bot stop. because i want to operate more than one bot simultaneously.so based on balance all bot will be stop. tq :)

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/37663385-dd3a4762-2c37-11e8-87e2-02fd0791ecfd.png)

[balances.xml.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1829920/balances.xml.zip)

**Comment by vajromchendroz** [comment]
why it won't stop ?
![balancetrial](https://user-images.githubusercontent.com/29012887/37693853-0e732af2-2cf5-11e8-91e1-7fefe9f7dd02.jpg)

**Comment by binary-ex-machina** [comment]
this strategy looks very risky, i don't know what more you are putting on it. Why not put a stop loss on each bot?

**Comment by vajromchendroz** [comment]
oh, that's not my strategy.it's only for the test. i use your hull ma indi for rainbow strategy, but if i use more than 3 hull ma the bot will run slowdown especially with hull ma above 100 ( it's look like crash). have you any suggestion ? and can you make based on ticklist ? thanks :)

**Comment by binary-ex-machina** [comment]
rainbow strategies uses a lot of indicators and of course more process from your computer to do the calculations. I don't think ticklist works in this case. My adivese is to now use so much indicators. 2-3 moving averages is the most you will need. All indicators where created for markets without expiration time on trades, what is not the case with binary options. Look for price action strategies.

**Comment by vajromchendroz** [comment]
of course i use indi for trigger when price action happen. thanks
