### ISSUE TITLE
indicators

### ISSUE THREAD

**Issue by Jonni81** [binary-ex-machina/binary.com-bot#19]
Hello. How to download your indicators? When I'm downloading in XML format I have, they do not open.

**Comment by binary-ex-machina** [comment]
After you load, appear the load block? did you look at the functions menu?

**Comment by Jonni81** [comment]
the fact of the matter is that none of their functions. maybe in some other browser to download? I have Yandex

**Comment by Jonni81** [comment]
Downloaded. But it does not appear in functions
![screenshot](https://user-images.githubusercontent.com/30568441/37860253-8468d950-2f43-11e8-9243-185c5e858c3f.png)

**Comment by binary-ex-machina** [comment]
what indicator you are trying to load?

**Comment by Jonni81** [comment]
https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/averate_true_range/atr.xml
and https://github.com/binary-ex-machina/binary.com-bot/blob/master/bots/9-high-success.xml and 
https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/fractal/fractal.xml

**Comment by Jonni81** [comment]
And this https://github.com/binary-ex-machina/binary.com-bot/blob/master/bots/1-multi-strategy-bot.xml

**Comment by binary-ex-machina** [comment]
ATR indicator loading fine
![image](https://user-images.githubusercontent.com/34610787/37866475-f1fe0e6a-2f69-11e8-919b-01f6508ad89e.png)

Higher bot loading fine

![image](https://user-images.githubusercontent.com/34610787/37866494-186c34fa-2f6a-11e8-9c28-4abc22ac19a6.png)

Multi Strategy loading fine

![image](https://user-images.githubusercontent.com/34610787/37866505-3546bd48-2f6a-11e8-8c69-0ffe6e6829f9.png)

Check your internet connection, ad block, browser. Everything works fine here on Chrome

**Comment by duynguyen2709** [comment]
Hey there I tested too and all is working fine. I think you should clear your browser's cache or change your browser.

**Comment by Jonni81** [comment]
https://yadi.sk/i/gkE0BnEa3TiW7E look

**Comment by Jonni81** [comment]
I tried using Yandex browser,Mozila,chrome. And nothing not broke a(((

**Comment by Jonni81** [comment]
I can only open when zip sent

**Comment by binary-ex-machina** [comment]
can you load other scripts?

**Comment by Jonni81** [comment]
no

**Comment by binary-ex-machina** [comment]
any other scripts? try open the bot page and download the file. the button is below the one that you use to load a script. then try to load it.

I can't help you more then that, it's no problem with my scripts

**Comment by Jonni81** [comment]
ok. thank you for your help and support binary-ex-machina
