### ISSUE TITLE
Trending market

### ISSUE THREAD

**Issue by janps1712** [binary-ex-machina/binary.com-bot#2]
Hi @binary-ex-machina 

Maybe you can help me with this. I dont want to make a trade when the market is trending og changing a lot in a short time. So I want to trade in a ranging market. Hope you understand :)

**Comment by binary-ex-machina** [comment]
I have created the  CHOP Indicator to know if is trending or on sideways. If it is on sideways, it will be very volatile, because it will be full of uncertainty.

the indicator works like this: Higher value = more on sideways

https://raw.githubusercontent.com/binary-ex-machina/binary.com-bot/master/indicators/chop/chop.xml

![chop](https://user-images.githubusercontent.com/34610787/35648960-a46176b6-06be-11e8-8a3b-58a7302732ec.png)

**Comment by janps1712** [comment]
Thank you. How do i use this with an rise/fall bot?

**Comment by binary-ex-machina** [comment]
it dependes on other indicators. the CHOP indicator just tells you about the trend and sideways

**Comment by janps1712** [comment]
Ok, I want to use it with SMA and RSI. Think I got it now. Again, thank you

**Comment by janps1712** [comment]
Is it possible to make this:

I want to start trading when the CHOP indicator is below 62 and keep trading as long the CHOP is descending. I take 5 tick trades.

Hope you understand what I am thinking :)

**Comment by binary-ex-machina** [comment]
It will trade every time the indicator is below 62 and the previous signal is higher then the actual

![image](https://user-images.githubusercontent.com/34610787/36356160-8b5821da-14cc-11e8-91b3-7ce53480c743.png)
[chop descending.xml.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1735048/chop.descending.xml.zip)

**Comment by janps1712** [comment]
Thank you. When I run it I get the message that "Given candle is not valid"

**Comment by binary-ex-machina** [comment]
change the close candles to the general candles
![image](https://user-images.githubusercontent.com/34610787/36356798-f353c524-14d5-11e8-8929-0bfcac403b94.png)

**Comment by janps1712** [comment]
Ok :)

If I want it to adapt quicker to changes in the market, should I then lower the period?

**Comment by binary-ex-machina** [comment]
lower periods are for short term trades
