### ISSUE TITLE
[bug] ATR Indicator 

### ISSUE THREAD

**Issue by duynguyen2709** [binary-ex-machina/binary.com-bot#20]
![screenshot_20180324104913](https://user-images.githubusercontent.com/31149300/37860089-1a6941c6-2f51-11e8-8c0e-4c3d511c4c3b.png)
![untitled](https://user-images.githubusercontent.com/31149300/37860090-1aa11f56-2f51-11e8-9b33-011ae4c7ab71.png)
Hey I've just tried your ATR Indicator and found a bug in it. The value calculation is right, but in Array mode it doesn't call the value of n(th) Candle ,instead it only show up the value of current candle (I called the 2th from end,3th from end,etc...). In these 2 images as you can see I called the 3th from end but it only calculate the current. 
btw thanks a lot for your tools and bots. I love them a lot 👍

**Comment by binary-ex-machina** [comment]
thank you for pointing it out. i've correct that
https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/averate_true_range/atr.xml

**Comment by duynguyen2709** [comment]
Yeah and I think you should take a look at other indicators about this problem too in order not to same the same bug 👍 Thanks so much :D
