### ISSUE TITLE
HELP DEVELOP MY TRADING STRATEGY

### ISSUE THREAD

**Issue by Adezking** [binary-ex-machina/binary.com-bot#21]
Hello Boss,

I am trying create this strategy below:

Market: Volatility 25 index
Timeframe: 2min

Binary Chart Setup
Indicators:Good support and resistance indicators(MACD,RSI,Bollinger band,ATR)
Candle TimeFrame: 2 Mins

Trading Rules
CALL Option (UP):

Price must start from the highest closing prices of the resistance level and close well above the region,indicating a breakout from the squeeze region.

The last candle in the region before the breakout must be green and the previous before that must be red.
TRADE
Buy CALL Option
Set expiration time: 2 Min

PUT Option (DOWN):

Price must start from the lowest closing prices of the support level and close well below the region,indicating a breakout from the squeeze region.

The last candle in the region before the breakout must be red and the previous before that must be green.
TRADE
Buy PUT Option
Set expiration time: 2Mins.

I'll be glad if YOU can help me set this up and pls put MARTINGALE and option to COMPOUND PROFITS.
I'LL SURELY DONATE TO UR GOOD COURSE IF I GET WHAT I WANT BOSS!
THANKS SIR

**Comment by Adezking** [comment]
Just to add that I will need it to pick trades only where there is high Volatility which means that it will require strong Volatility indicators as well as support And resistance indicators. I don't know much about indicators,I only suggested few that I think I know,pls use your expertise for me sir.Thanks for your help.

**Comment by binary-ex-machina** [comment]
> Indicators:Good support and resistance indicators(MACD,RSI,Bollinger band,ATR)

RSI, MACD, BB, ATR are not indicators for support and resistance.

> Price must start from the highest closing prices of the resistance level and close well above the region,indicating a breakout from the squeeze region.

this is very hard to put on the bot, the bot works with numbers, no region. If it hits X number, it do something. That's the logic.

your strategy is too complex to implement

**Comment by Adezking** [comment]
Thank you so much for your prompt response Boss.I perfectly understand your
explanation.

Now,can you help me build a binary tick trade bot with 5 conservative
martingale recovery plan?

E.g if I stake $0.5 and it lost,the bot will use x10 and if lost again it
will stake x10 and if lost again it will stake 10 up to 5 recoveries.

E.g: 0.5,1,10,100,1000

Secondly if it's possible to include the option of compounding the
profits,It will really be useful.

Thank you so much boss.

**Comment by binary-ex-machina** [comment]
what? x10 on loss? if you loss five times: $5, $50, $500, $5000, and then bet $50000? really?

**Comment by Adezking** [comment]
Lol...I intend to start from 0.5 on the differ market and I believe it
can't lost 5 times in a row...

What are the best indicators for support and resistance boss?

**Comment by Adezking** [comment]
These are examples of the breakout price movements I was trying to explain
boss,but I understand it may be very complex to build.

**Comment by binary-ex-machina** [comment]
there aren't support resistance indicators. You can find some that place this on chart, but calculate them is complex on binary.com. When you are creating a strategy, imagine the worst case scenario, then the worst case scenario after that, then be prepared to loose at least 10 times in a row. then be prepared to loose at least 15 times in a row. I got number 0 six times in a row on digits, trying differ with approach like you wrote. It will destroy your account.

**Comment by Adezking** [comment]
Hnmmm....thank you very much sir,I really appreciate your help and
concern.May God continue to bless you.
Now,which of all the strategies that you have built do you think is a bit
safe and that can be left to run automatically and you can advise me to
make use of?

I know there is no perfect strategy.I only need something that can make
consistent profits,no matter how little and can run on it's own.

Thanks once again for your help boss.

**Comment by Adezking** [comment]
![whatsapp image 2018-03-19 at 1 01 30 pm](https://user-images.githubusercontent.com/37736169/37878782-1df27144-3066-11e8-830a-dada62437bb1.jpeg)
![whatsapp image 2018-03-19 at 1 01 33 pm](https://user-images.githubusercontent.com/37736169/37878787-33f1d0d4-3066-11e8-9fb1-a8dbebd822da.jpeg)

**Comment by binary-ex-machina** [comment]
It's hard to use only one strategy. All my bots are good, if you play them in the right time. The main idea to use a bot is to make trades faster then you and to set you free of looking to a screen all day. The less riskier strategies are the ones that you stay very short on the market, make a lot of trades, or that ones that you make less trades during the day, but stay long on the market to enter in the best periods. So you will need not 1, but some bots and define a strategy for all the scenarios and when to trade them
