### ISSUE TITLE
[Bug] Labouchere Money Management

### ISSUE THREAD

**Issue by duynguyen2709** [binary-ex-machina/binary.com-bot#23]
Hey it's me again :D I tested ur Labouchere MM and found a bug : the stake remained the same on every trades. I was sure I did nothing wrong so could u please give it a check :D 
P/S : I implemented my own Labouchere source code already . This issue is for notify about the bug only :D

**Comment by binary-ex-machina** [comment]
I've tested here and everything works great


![image](https://user-images.githubusercontent.com/34610787/39401544-dc5961e8-4b1d-11e8-980e-2cb703583fec.png)


![image](https://user-images.githubusercontent.com/34610787/39401541-d50cfea4-4b1d-11e8-8883-1f319422a962.png)

![image](https://user-images.githubusercontent.com/34610787/39401546-e66ccac6-4b1d-11e8-8e1d-ef97eef0f6bc.png)
