### ISSUE TITLE
even/odd strategy 

### ISSUE THREAD

**Issue by Aloyjoe** [binary-ex-machina/binary.com-bot#24]
please help me build this even odd binary.com strategy.
the strategy  goes like this. 1. if the last digit is 1 do purchase even 2. if the last is 0 do purchase odd, 3. if the last is 2 do purchase even, 4. if the last digit is 3 do purchase odd 5. if the last digit is 4 do purchase even, 6. if last is 5 do purchase odd, 7. if the last digit is 6 do purchase even, 8. if the last digit is 7 do purchase odd, 9. if the last digit is 8 do purchase even, 10. if the last digit is 9 do purchase odd. add martingale with martingale level set to 4. thanks

**Comment by binary-ex-machina** [comment]
there is no logic in you strategy. You really believe that when last digit is 1, the 6th after that will be 1?
really?
