### ISSUE TITLE
SMA strategy 

### ISSUE THREAD

**Issue by Aloyjoe** [binary-ex-machina/binary.com-bot#25]
please build this simple moving average bot for me.
we will use simple moving average 20, 40, and 80 here is the strategy, if price is above the 3 simple moving average 20, 40, and 80 simple moving average purchase rise, if price is below 20,40 and 80 simple moving average purchase fall.

**Comment by binary-ex-machina** [comment]
this wont work on binary options. You have expiration time. How much is that? what the candle time? Just asking for a bot with a strategy based on moving averages wont help.
