### ISSUE TITLE
trailling stop

### ISSUE THREAD

**Issue by vajromchendroz** [binary-ex-machina/binary.com-bot#27]
can you teach me to an example for trailling stop ? thanks :)

**Comment by binary-ex-machina** [comment]
google has the answer

https://www.investopedia.com/video/play/how-use-trailing-stops/

**Comment by vajromchendroz** [comment]
that's good, i mean example on logic binary bot . such as now my bot win $15, if my profit reduced by $5 my bot will stop for security win. i hope you know what i think. thanks ...

**Comment by binary-ex-machina** [comment]
this doesn't have any logic for trailing stops. Just put a positive stop loss and you good.

**Comment by vajromchendroz** [comment]
aha ... thanks
