### ISSUE TITLE
Spot Price Analyzer BOT

### ISSUE THREAD

**Issue by akh2018** [binary-ex-machina/binary.com-bot#28]
Hello ,

I need to make BOT for my magic Spot price analyzer strategies.
Please send e-mail to me : akhnetbuster@gmail.com if you are interesting.
Thanks you

**Comment by binary-ex-machina** [comment]
post the strategy here

**Comment by akh2018** [comment]
pls write me your e-mail or reply to my e-mail mentioned to you.This strategy are valuable and private.

Thanks you
