### ISSUE TITLE
How to add Stop Loss Counter and Reset to initial stake

### ISSUE THREAD

**Issue by pierhans** [binary-ex-machina/binary.com-bot#3]
@binary-ex-machina 
I tried to add the martin.xml.zip you provided for the Stop Loss Counter reset to one of your Bot, but I failed miserably. I tried to add it to your bot #5-redgreen.xml but if it loses once it resets right away. Can you help 
[binary-bot help Ex-Machina.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1686009/binary-bot.help.Ex-Machina.zip)

Thank you so much ! I love all your Bots

**Comment by binary-ex-machina** [comment]
You need to put the martingale function above all and change the stake multiplier of the martingale to the main stake. Also change the Trade Gain function to the losses checking.

![join](https://user-images.githubusercontent.com/34610787/35686490-862af1e6-0753-11e8-9403-ce7880e416df.png)

**Comment by pierhans** [comment]
It worked !!!!!!!!!!!! 
Thank you so so much @binary-ex-machina ! I told my friends you were the Best! I will contribute to your Gumroad peodilw as soon as profit starts coming in with the bot. Thank you so much again 🥇

**Comment by binary-ex-machina** [comment]
thank you and please, post your results, i'm testing your strategy too!
