### ISSUE TITLE
PLS EDIT BOT

### ISSUE THREAD

**Issue by Adezking** [binary-ex-machina/binary.com-bot#31]
Hello boss @binary-ex-machina ,can you please help me  edit this  BOT to pick just one trade per signal instead of 3 in a row as originally built and trade again when new signal forms after a while ? thanks in anticipation of your prompt response.

[9-high-success.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1866418/9-high-success.zip)

**Comment by binary-ex-machina** [comment]
thanks for using my bot. what you want can't happen with the bot.

> One trade per signal
this is what he already does. It only passes the block 1 after get the signal.

> trade again when new signal forms after a while
Already doing that.

What you want is that it don't trade all that candle that he enters. The main problem is that you need to set the best time to enter and this can vary.

![image](https://user-images.githubusercontent.com/34610787/38175838-7cc1a868-35b9-11e8-89b1-942376fed449.png)

Putting the bot that checks the seconds, can limit the trade to happen only before the 20 seconds of the candle. Most of the time will get only one trade, but need to test the value (20 seconds)

**Comment by Adezking** [comment]
Thanks for ur prompt response,I'll test the -20seconds bot and see how it goes..thanks again sir
