### ISSUE TITLE
HighLow wrong purchasing

### ISSUE THREAD

**Issue by duynguyen2709** [binary-ex-machina/binary.com-bot#32]
![screenshot_20180403192626](https://user-images.githubusercontent.com/31149300/38249440-dd054582-3775-11e8-97cd-27bbe14aeb42.png)
![q12131](https://user-images.githubusercontent.com/31149300/38249438-dcca5c24-3775-11e8-9917-54bbc458f22a.png)
![123412](https://user-images.githubusercontent.com/31149300/38249437-dc8f18a8-3775-11e8-80cf-86786590659d.png)

Hey it's me again, but this time is a help-needed, not a bug found :D
Having hard time to find out what I'm doing wrong here. My idea is when I purchase Higher than it would be : Higher than (Entry + 1) ; and for Lower is : Lower than (Entry - 1).
However the bot is running like "random" (or if I have made mistake somewhere without realising ?) .
Also tried to put negative number in the barrier and had no success.
Any help would be appreciated :D

**Comment by binary-ex-machina** [comment]
same here: https://github.com/binary-com/binary-bot/issues/630
