### ISSUE TITLE
This strategy is having a Break Even win ratio

### ISSUE THREAD

**Issue by thehightechsol** [binary-ex-machina/binary.com-bot#33]
The following code is giving me a break even results . Basically it is a trend follow strategy. And I didnt code  it to avoid lateral or choppy market. If someone point out a condition to insert a code to avoid lateral or choppy market it would perform better. I might insert 50 ema but any other suggestions
![screenshot_9](https://user-images.githubusercontent.com/9295806/38464475-4b1f0f30-3b2c-11e8-86b5-040732a8c236.png)
![screenshot_10](https://user-images.githubusercontent.com/9295806/38464476-4b56ffc6-3b2c-11e8-87d7-96dc19af50e7.png)

**Comment by binary-ex-machina** [comment]
use the Chop Indicator https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#chop-indicator
