### ISSUE TITLE
stochastic stop working after Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by nextnaro** [binary-ex-machina/binary.com-bot#34]
stochastic stop working after "Cannot read property 'slice' of undefined".
i print out every tick test indicator. after the message show not result from indicator show.
i use  KD both 5,3,3 and test another value same error.

**Comment by binary-ex-machina** [comment]
I'm testing here and it's working very nicely

![image](https://user-images.githubusercontent.com/34610787/39401560-4291fcc2-4b1e-11e8-9e95-ecfac26219f8.png)

Post a print of your blocks
