### ISSUE TITLE
i need help please

### ISSUE THREAD

**Issue by kings4ril** [binary-ex-machina/binary.com-bot#35]
hello can someone assist me, i want to convert my  rise/fall strategy to a bot. here is my chart 
![binary](https://user-images.githubusercontent.com/29650386/39155306-5d52ecac-4749-11e8-990b-76a451b1711b.jpg)    please can it worked? i use ma 13, ma21 and ma50. my entry point are marked on my chart snapshot  if you want to help, you can reach me here kings4ril111q@yahoo.com

**Comment by binary-ex-machina** [comment]
send an email to binaryexmachina@gmail.com
