### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Jonni81** [binary-ex-machina/binary.com-bot#4]
Hi! Wanted to know how to install your indicators?

**Comment by binary-ex-machina** [comment]
• click to load the script

![open](https://user-images.githubusercontent.com/34610787/35917433-46ea9512-0bf5-11e8-9140-f56edb3ff08c.png)

• Select the indicator
• Look on the functions menu 

![menu](https://user-images.githubusercontent.com/34610787/35917479-758a2fae-0bf5-11e8-83e3-a5af6650f020.png)

take a look on the [wiki](https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators) for more info about each indicator
