### ISSUE TITLE
Minute Candle

### ISSUE THREAD

**Issue by csajkas** [binary-ex-machina/binary.com-bot#40]
Hi @binary-ex-machina 

Please help me,

This is correct so? 
![easycapture1](https://user-images.githubusercontent.com/35691604/42556862-3f47d088-84ed-11e8-9445-2b4323ce3cc2.jpg)

I want to buy if a minute candle is closed and closed price is higher then EMA 50 and EMA 10,bot must  check only close price and open position if closed price is good. Created few bots but with ticklist and I dont have experience with minute candle systems.

Thank you

**Comment by binary-ex-machina** [comment]
with this you enter at the end of the minute. The rest of your strategy is correct for what you want.

![image](https://user-images.githubusercontent.com/34610787/42576950-f603c492-84f9-11e8-85fc-8bcefef5c822.png)

**Comment by csajkas** [comment]
Thank you @binary-ex-machina, you are the best :+1:
