### ISSUE TITLE
Candle Strategy

### ISSUE THREAD

**Issue by csajkas** [binary-ex-machina/binary.com-bot#46]
Hi Master :) 

I want to ask you, what is wrong in my code? 

My idea is: 
1 or 5 minute candles! 

If 3 candle is green and 4. candle is red then PUT
if 3 candle is red and 4. candle is green then CALL.

[Count Candle.zip](https://github.com/binary-ex-machina/binary.com-bot/files/2305415/Count.Candle.zip)

**Comment by wijanarkokns** [comment]
Do you mean candle 4 = the last candle? maybe like this ...
[Issue #46 binary ex-machina.txt](https://github.com/binary-ex-machina/binary.com-bot/files/2306356/Issue.46.binary.ex-machina.txt)

**Comment by csajkas** [comment]
Yes @wijanarkokns 
Thank you
