### ISSUE TITLE
 wrong cci data 

### ISSUE THREAD

**Issue by rasjohse** [binary-ex-machina/binary.com-bot#49]
hello ex machina, your work is quite extensive and of great help to the community, I have a problem with the CCI that you facilitated, because the reading of the calculation is quite different, if you could give me some advice to improve this, I would be grateful, another problem is that when my mobile averages are crossed they do not run if not until the next candle, they are not in array, if you could advise me at some time that you have, I would be grateful.

In advance very good work you do and your contributions are a great springboard to build our bots.

**Comment by binary-ex-machina** [comment]
Don't use arrays if you want to get just one value. 

the calculation of the CCI is from here https://www.investopedia.com/terms/c/commoditychannelindex.asp
