### ISSUE TITLE
build this EMA strategy for me please

### ISSUE THREAD

**Issue by Aloyjoe** [binary-ex-machina/binary.com-bot#5]
please help me build this ema strategy to a bot
if 25 EMA is above 50 EMA and both 25 and 50 EMA is Above 100 EMA do purchase rise on the next candle.
and If 25 EMA is below 50 EMA and both 25 and 50 EMA is below 100 EMA do purchase fall on the next candle. please add martingale thanks

**Comment by binary-ex-machina** [comment]
It will purchase on the beginning of the next candle if the conditions met.


![abovebelow](https://user-images.githubusercontent.com/34610787/35917384-08f137ca-0bf5-11e8-9d10-6df4b6d27ea5.png)


[abovebelow.xml.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1703115/abovebelow.xml.zip)
