### ISSUE TITLE
How to create max or min in list

### ISSUE THREAD

**Issue by navneetsinh** [binary-ex-machina/binary.com-bot#57]
how to use max/min/avg of list 
if possible please send me some example of blocks.
thanks

**Comment by binary-ex-machina** [comment]
here is an example of use of the max/min/average using a sub list of the latest 5 ticks.

![image](https://user-images.githubusercontent.com/34610787/50729045-3eaf2b80-111a-11e9-9f9c-f464d666e944.png)

**Comment by navneetsinh** [comment]
@binary-ex-machina Thanks
