### ISSUE TITLE
About Tick List

### ISSUE THREAD

**Issue by navneetsinh** [binary-ex-machina/binary.com-bot#58]
RSI Ticks List 10
Overbought : 50
Oversold : 50

I want avg list of rsi 10 which ticks rsi10>50.
Only the rsi10 ticks which are above 50 overbought.
Total last 21 ticks which are >50 not any of ticks
<50.
Can it possible only for upper ticks rsi10>50 last 21 upper ticks

**Comment by binary-ex-machina** [comment]
here is an example of the use of RSI10, to get the last 21 values of the indicator above or below the 50 line

![image](https://user-images.githubusercontent.com/34610787/50795534-b1a0d980-12b5-11e9-9f0e-73cf76453b76.png)

**Comment by navneetsinh** [comment]
hi again, 
thanks for helping
your given solution is not working please check if I forgot to doing something.
![rsi](https://user-images.githubusercontent.com/42480287/50815263-7993a800-1342-11e9-9fd7-194ce32f139e.png)
