### ISSUE TITLE
About Barrier Setting

### ISSUE THREAD

**Issue by navneetsinh** [binary-ex-machina/binary.com-bot#59]
How can we set lowest barrier on starting of bot. any volatility or any market.
we don't need to check, once we start to run bot and it takes auto as lowest barrier. Any blocks setting for that.

Another question : running bot with lowest barrier and in between barrier pipes change, and we get error message for barrier is not valid. on that point it can possible auto change lowest barrier and continuous run the bot.

**Comment by binary-ex-machina** [comment]
1. You can't get the lowest barrier possible with the blocks, you need to set manually.

2. If you get barrier not valid is because you are setting it wrong. Again, you can't get the lowest barrier possible automatically.

**Comment by navneetsinh** [comment]
> 
> 
>     1. You can't get the lowest barrier possible with the blocks, you need to set manually.
> 
>     2. If you get barrier not valid is because you are setting it wrong. Again, you can't get the lowest barrier possible automatically.

thanks for your reply on my question.
