### ISSUE TITLE
help

### ISSUE THREAD

**Issue by laxracorp** [binary-ex-machina/binary.com-bot#6]
please do you have psar bot?
can you share?
thanks

**Comment by binary-ex-machina** [comment]
I don't have this indicator. It's a very complex one.

**Comment by laxracorp** [comment]
but please can you make your stochastic bot to trade cross,i have tried to modify it to trade but it is always wrong.

**Comment by binary-ex-machina** [comment]
trade cross is too vague so I assume you want to trade rise, when K signal crosses up D signal and fall when K crosses down D. Stochastic alone doesnt work well. Also this indicator is not 100% accurate, so you may find distortion. If you choose to get both signals from indicator, it will receive an Array [K,D]. 

![stoch](https://user-images.githubusercontent.com/34610787/35924083-2f7e3dfc-0c09-11e8-904c-fbc1b1abb6ad.png)

**Comment by laxracorp** [comment]
THIS IS THE FIBONACCI BOT THAT I MADE,@BINARY EX MACHINA,CAN YOU CHECK IF LOGIC AND CALCULATION IS CORRECT?

**Comment by laxracorp** [comment]
please how can i attach files,i want to attach bot  or picture

**Comment by binary-ex-machina** [comment]
change the extension to .txt or compress the file (.rar .zip)

**Comment by CorreiaMerchant** [comment]
@laxracorp,

Poste seu arquivo para que possamos analisar e ajuda-lo
