### ISSUE TITLE
About EMA Stratery

### ISSUE THREAD

**Issue by navneetsinh** [binary-ex-machina/binary.com-bot#60]
Ema 14 cross down Ema 21 Trade with Fall
Ema 14 cross Up Ema 21 Trade with Rise

I tried with making this strategy by my bot but it's also trades on EMA14 > EMA21 OR  EMA14 < EMA21. I want only trade on **cross up/cross down**.
I don't want to trade on EMA14 > EMA21 OR  EMA14 < EMA21. 

If possible please help me.
Thanks,

**Comment by binary-ex-machina** [comment]
You can get the cross comparing the 2nd element of the two arrays you want to compare, then compare the 1st element (actual value) to see if it was cross over or cross under

![image](https://user-images.githubusercontent.com/34610787/50795326-055ef300-12b5-11e9-81e1-199b72883736.png)

**Comment by navneetsinh** [comment]
> 
> 
> You can get the cross comparing the 2nd element of the two arrays you want to compare, then compare the 1st element (actual value) to see if it was cross over or cross under
> 
> ![image](https://user-images.githubusercontent.com/34610787/50795326-055ef300-12b5-11e9-81e1-199b72883736.png)

here is both purchase condition with rise ?????

**Comment by binary-ex-machina** [comment]
@navneetsinh my mistake, the second is fall.

**Comment by navneetsinh** [comment]
@binary-ex-machina ok, done, thank you
