### ISSUE TITLE
Need a volume indicator

### ISSUE THREAD

**Issue by shonOXO** [binary-ex-machina/binary.com-bot#62]
i need a volume indicator or related indicator to volume.plz @binary-ex-machina

**Comment by binary-ex-machina** [comment]
please specify what volume indicator you need. Volatility Indexes doesn't have volume and forex markets have, but you can't get the value with the blocks

**Comment by shonOXO** [comment]
oh i dont know that .i thought volattility markets have it.so are there any kind of indicator can  related focus volatility index 100
