### ISSUE TITLE
please modif my bot

### ISSUE THREAD

**Issue by yudiaswar** [binary-ex-machina/binary.com-bot#63]
please  if lose, change and replace the digit prediction. Thanks

[last-digit-over-under (1).zip](https://github.com/binary-ex-machina/binary.com-bot/files/2824179/last-digit-over-under.1.zip)

**Comment by binary-ex-machina** [comment]
change and replace by what?

**Comment by binary-ex-machina** [comment]
well, here is the logic that will change over > under or under > over when a loss occur. You can apply this to any bot that uses under/over

![image](https://user-images.githubusercontent.com/34610787/52166364-62529b00-26f3-11e9-8514-37bbd8088b20.png)
