### ISSUE TITLE
how to start bot after some ticks

### ISSUE THREAD

**Issue by navneetsinh** [binary-ex-machina/binary.com-bot#64]
how to start bot after some ticks
help me for creating some blocks for run bot after some ticks.
example : starting a bot(after pressing play button) and wait for 7 or 8 ticks (but run strategies in background) than play bot
this is for first time only

**Comment by binary-ex-machina** [comment]
In the example below, when the counter hits 10, it will enable the bot to purchase Rise. The calculation of the RSI and the verification of the value will continue on every tick until the contract is bought.

![image](https://user-images.githubusercontent.com/34610787/53253335-ba037700-369f-11e9-9f03-e3f18c21cd95.png)

**Comment by navneetsinh** [comment]
Thanks dear
