### ISSUE TITLE
Create bot high low last 5 candle

### ISSUE THREAD

**Issue by yudiaswar** [binary-ex-machina/binary.com-bot#65]
Hi master.please Create bot high low last 5 candle.thanks

**Comment by yudiaswar** [comment]
Identify  last 5 candle  before open position. If toutch high last 5 candle purcase call if low fall

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/53252940-dbb02e80-369e-11e9-9d28-1b464c88a4f9.png)

**Comment by yudiaswar** [comment]
What is this seconds since epoch ÷60 > 57?

**Comment by yudiaswar** [comment]
Hii master. Help me,,If lost 3 , wait next candle open position.thanks
