### ISSUE TITLE
Please help me.. to edit bot

### ISSUE THREAD

**Issue by marivey** [binary-ex-machina/binary.com-bot#66]
@binary-ex-machina 
Please help edit the binary-com/binary-bot#989 does not want to analyze the new candle again after win / loss.

Please make:
1. If win, immediately analyze the new candle again and op with a fixed stake.
2. If loss, immediately analyze the new candle again and op with the stake in martingale.

Thank you ... please if the other masters can help me

**Comment by binary-ex-machina** [comment]
i don't know about that bot, but below is the logic that will trade one time per candle, reseting the stake to 1 when a win occur and multiplying by 2 when a loss occur.

![image](https://user-images.githubusercontent.com/34610787/53683128-1851da80-3cdc-11e9-81f4-95bc37b5df41.png)

**Comment by marivey** [comment]
Can I make binary bots with rules:
 
1. Analyze the TF candle 1 minute.

2. If the closing price of the 1 minute candle forms maburozu and the color of the red candle, Op rise in new candle duration 57 seconds.

3. If the closing price of the 1 minute candle forms maburozu and the color of the green candle, op fall in new candle duration 57 seconds.

4. If win, trade again, with the first stake, with the same analysis as points 2 and 3.

5. If loss, trade again, with a stake (first stake x 2.09), 4 levels of martingale, with the same analysis as points 2 and 3.

Please help me. Thank you in advance.
