### ISSUE TITLE
How to close a Expiry range trade in profit before the normal expiry time ends

### ISSUE THREAD

**Issue by hmebert1980** [binary-ex-machina/binary.com-bot#68]
Hi @binary-ex-machina,

Please see the image below.

![image](https://user-images.githubusercontent.com/44832799/54697411-86f3bc80-4b53-11e9-8000-3736e6109127.png)

I think the trades are with 3 min expiry and closes early during the first minute with the "Sell at market" command. I am trying to replicate the bot using 3 min expiry, $2.50 stake, and different barriers, Buts still am unable to get the expected profit within the first minute because binary.com doesn't offer "sell at market" on the last 2 minutes when "Digits" -> "Ends In" is selected. I could surely use your help.

**Comment by binary-ex-machina** [comment]
If binary.com doesn't offer sell at the market in the last 2 minutes, choose another contract type. You can't overrun their rules in trading on their platform.
