### ISSUE TITLE
Max Martingale 2 and reset

### ISSUE THREAD

**Issue by Fraga2** [binary-ex-machina/binary.com-bot#69]
Hello, I would need to restart it in the second martingale and start over, I'm very bad at joining and programming. Would be:
-0.37
-2.22
-13.32
-0.37
...
[bot_under_prediction_analyzer.txt](https://github.com/binary-ex-machina/binary.com-bot/files/3110301/bot_under_prediction_analyzer.txt)

**Comment by binary-ex-machina** [comment]
![image](https://user-images.githubusercontent.com/34610787/56871963-15344b80-69fa-11e9-8b85-abf489efc342.png)
