### ISSUE TITLE
Stocahstic

### ISSUE THREAD

**Issue by armmar4711** [binary-ex-machina/binary.com-bot#7]
How to create stochastic 5,3,3 if over 80 trade fall if under 20 trade rise
I do not know how to put the period on your indicator

**Comment by binary-ex-machina** [comment]
download the indicator again, i've added the inputs

**Comment by armmar4711** [comment]
is it true 




[binary-bot (4).zip](https://github.com/binary-ex-machina/binary.com-bot/files/1703722/binary-bot.4.zip)

**Comment by binary-ex-machina** [comment]
you have to get D not Both

**Comment by armmar4711** [comment]
lengeht 5 smooth K3 D3 right?

**Comment by binary-ex-machina** [comment]
yes, it works better with 14,1,3

**Comment by armmar4711** [comment]
Ok. I will try.
Thank you for your kindness
