### ISSUE TITLE
Please help me create a bot using the ADX indicator just like the binary floor parameter

### ISSUE THREAD

**Issue by giaupn** [binary-ex-machina/binary.com-bot#71]
Please help me create a bot using the ADX indicator just like the binary floor parameter
![image](https://user-images.githubusercontent.com/45723837/56855828-8b906980-6978-11e9-812c-ff92cca82c35.png)

**Comment by giaupn** [comment]
@binary-ex-machina

**Comment by binary-ex-machina** [comment]
It's not possible to create this indicator in the blocks.
