### ISSUE TITLE
binary bot martingale ! 

### ISSUE THREAD

**Issue by maximusa1** [binary-ex-machina/binary.com-bot#77]
hello i need help about binary bot XML  file .. i have created on website but martingale is 2.0x so i want low marti.. who can help me setup tabs there and i will choise in each tab what amount number to put ... ?  who can help me skeleton for martingale tabs its eazy i think ..

**Comment by esanshogo** [comment]
Please anyone help me too that support xml file, by sending it to esanshogo@gmail.com  thanks to you all

**Comment by boyotoju** [comment]
Please I'll like to receive some nice bots too
toritsejubi@gmail.com
Thanks

**Comment by binary-ex-machina** [comment]
here it is a very basic example of how to make martingale on any bot. After a loss it will multiple the stake by the number on martingale variable. When it wins, it will set the stake to the initial value

![image](https://user-images.githubusercontent.com/34610787/69402330-4518a880-0cd6-11ea-8797-b2cb042360de.png)

**Comment by Shuckoswaldo** [comment]
> Aquí es un ejemplo muy básico de cómo hacer martingala en cualquier bot. Después de una pérdida, multiplicará la apuesta por el número en la variable martingala. Cuando gane, establecerá la apuesta al valor inicial
> 
> ![imagen](https://user-images.githubusercontent.com/34610787/69402330-4518a880-0cd6-11ea-8797-b2cb042360de.png)

como realizó martingala que solo me recuperé el valor perdido y poder usar en varios marcados tanto digitos como call put
