### ISSUE TITLE
 Problem to create list

### ISSUE THREAD

**Issue by rasjohse** [binary-ex-machina/binary.com-bot#79]
hello mr, I need help to create a list of an individual value, I managed to create that list, but it does not save the previous ones but it repeats the same input data in the whole list, I would be grateful if you can direct me on how to create the list, thanks
![REPEAT-IN-LIST](https://user-images.githubusercontent.com/33709714/62594256-e4409e00-b8a7-11e9-8f58-6f089b176e2a.png)

**Comment by binary-ex-machina** [comment]
You are setting the variable where you are inputing the values as Empty List every time you call this function, that's why it keeps refreshing all the time

![image](https://user-images.githubusercontent.com/34610787/69402191-d76c7c80-0cd5-11ea-821e-cf0cdbc38fff.png)
