### ISSUE TITLE
Stochastic indicator returns wrong values

### ISSUE THREAD

**Issue by FloPinguin** [binary-ex-machina/binary.com-bot#8]
At the moment I'm trying out your indicators. Great work, I really appreciate it.

But I found out that your stochastic indicator returns wrong values. I compared it with the stochastic indicator of trading view. Can you please look into it? I tested it with 1 minute candles and the inputs 14, 1, 3.

If you get it working correctly and I can use my stochastic strategy, I will probably leave a donation :)

**Comment by binary-ex-machina** [comment]
@FloPinguin test again https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/stochastic/stochastic.xml

I've updated and it's working nicely with 14,1,3

**Comment by FloPinguin** [comment]
Hello,

thanks, I tested it. It's working 100% accurate with 14,1,3. Great! But now I tried it with 19,3,3 (Smoother variant). It's returning wrong values. To be specific: 14,1,3 returns the EXACTLY SAME values as 19,3,3. Can you make it working with different function inputs?

**Comment by binary-ex-machina** [comment]
@FloPinguin I left some static values. Download again and try it. https://github.com/binary-ex-machina/binary.com-bot/blob/master/indicators/stochastic/stochastic.xml

**Comment by FloPinguin** [comment]
It's working now!
