### ISSUE TITLE
Help For Learn Loop Blocks

### ISSUE THREAD

**Issue by navneetsinh** [binary-ex-machina/binary.com-bot#80]
Please help me to learn Loop Blocks,
How does this block work?
And where can this block be used?
If possible give a example.

https://github.com/binary-com/binary-bot/issues/1935

**Comment by binary-ex-machina** [comment]
The block will count from the number you put until it reaches the other number you input, by the number you use

This example shows the bot counting from 1 to 10, 1 step at the time (it will read whats inside of the loop block 10 times) and a green alert will come with 10

![image](https://user-images.githubusercontent.com/34610787/69402103-9bd1b280-0cd5-11ea-867e-52171702aa7c.png)
