### ISSUE TITLE
Bot script

### ISSUE THREAD

**Issue by yusufali1234** [binary-ex-machina/binary.com-bot#81]
2 bot stops together when  themain balance increase by 1$

**Comment by esanshogo** [comment]
Give it to me

**Comment by Tebu1429** [comment]
Hi.
Could I also have it?

Thank you!

**Comment by yusufali1234** [comment]
Sir I want the script for this concept or if u can help me to create such

**Comment by binary-ex-machina** [comment]
It's impossible to have this working in any occasion

**Comment by yusufali1234** [comment]
What if set a veriable name balance =balance number+1
Then on trade result
If balance number>balance
 Set tick to 100
It will make both the bot to stop together when balance increase by 1
I have put this blocks in both the bots n they work but its not accurate i mean i need to make it perfect....
