### ISSUE TITLE
Auto Trader Web

### ISSUE THREAD

**Issue by binary-ex-machina** [binary-ex-machina/binary.com-bot#85]
My main since 2018 is my own system for trading binary options. the idea is to have tools to help trading and getting better analysis and no delays

https://www.binarybot.online

I'll not update the .xml in this repository regularly or answer all the issues here, since I don't have much free time.

**Comment by jmarcosoliver** [comment]
man... can you make a bot for us that see 2 last candle with same collor + 1 candle with different collor and after this pattern is complete, purchase to same direction of that 2 candles of same collor? (with martingalle)  wtzp +55 41991061920  (nick olijma)
take a look at my attached jpg please
tnk u so much....
![ineditus strategy](https://user-images.githubusercontent.com/48003032/72223508-59e32100-354e-11ea-90cf-bfe371a7a75f.jpg)

**Comment by gabinasky-78** [comment]
Hello bro. Really interested in your work and your valuable contributions on this forum. Pls how do I reach u via email? Thanks

**Comment by jmarcosoliver** [comment]
> 
> 
> Hello bro. Really interested in your work and your valuable contributions on this forum. Pls how do I reach u via email? Thanks

WTZP +55 41 99106-1920
