### ISSUE TITLE
Side Trend HELP.

### ISSUE THREAD

**Issue by Kikoorulio** [binary-ex-machina/binary.com-bot#87]
Hello I need to put a setting that the bot informs me and does not operate with the 5 minute chart lateralized, it can only operate in up or down trend.

@binary-ex-machina

**Comment by binary-ex-machina** [comment]
How will you identify the sideways market?

**Comment by Kikoorulio** [comment]
Yes I want that when the market is lateral the bot does not operate

**Comment by binary-ex-machina** [comment]
@Kikoorulio imagine if i could get that with the precision you want? i would be millionarie right now. It's impossible to have such configuration working 100% right and if you can't trade only on certain market moments, there is no reason to use it.

You want something that is not possible. It's like to say "i want to play a strategy that makes money on up trending market, only during up trend" or "i want to trade only on times where i make money" or "i want to avoid all the times i could lose"

it's not possible

**Comment by Kikoorulio** [comment]
Thanks my bro
