### ISSUE TITLE
Help me bot stop

### ISSUE THREAD

**Issue by Kikoorulio** [binary-ex-machina/binary.com-bot#88]
I need a setting where the bot enters the first few seconds of the next candle. I use this image, but the bot does some operations later and doesn't work anymore.

![image](https://user-images.githubusercontent.com/58524253/70165307-72376480-16a1-11ea-953c-38dd41514ac8.png)

@binary-ex-machina

**Comment by binary-ex-machina** [comment]
Use it like this

![image](https://user-images.githubusercontent.com/34610787/70391884-ae780700-19b8-11ea-9c4b-20c19a3c5878.png)

**Comment by Kikoorulio** [comment]
Very thanks
