### ISSUE TITLE
Candle + EMA Strategy

### ISSUE THREAD

**Issue by LCavanholi** [binary-ex-machina/binary.com-bot#89]
1 minute candle strategy.

If 3 consecutive bullish candlesticks are above the 20-period EMA: bet upwards on the next candlestick.

If 3 candlesticks in sequence are below the 20-period EMA: bet down on the next candlestick.

Warning: A new bet should only be placed if this sequence is broken with a candle of opposite color.

PT/BR
Candle de 1 minuto.

Se 3 candles de alta em sequência estiverem acima da EMA de 20 períodos: aposte para cima, no próximo candle.

Se 3 candles de baixa em sequência estiverem abaixo da EMA de 20 períodos: aposte para baixo, no próximo candle.

Atenção: uma nova aposta só deve ser feita se essa sequência for quebrada com um candle de cor oposta.

**Comment by binary-ex-machina** [comment]
você pode usar esta logica abaixo para fazer a analise the 3 candles da mesma cor acima/abaixo do EMA, entrando com CALL/PUT

![image](https://user-images.githubusercontent.com/34610787/70391870-8a1c2a80-19b8-11ea-9537-d7ade7c5cd69.png)
