### ISSUE TITLE
Stochastic up down

### ISSUE THREAD

**Issue by janps1712** [binary-ex-machina/binary.com-bot#9]
![image](https://user-images.githubusercontent.com/34183469/36394952-e0b4b4d2-15b6-11e8-95ac-dcbb3ee18997.png)

Is this possible with your Stochastic indicator?
Rise when %K crosses above %D
Fall when %K crosses bellow %D

It can happen anywhere and not import if it is in overbougt or oversold.

**Comment by binary-ex-machina** [comment]
Adjust the duration and the candle time

![image](https://user-images.githubusercontent.com/34610787/36486742-03349660-16fe-11e8-9e73-caf1c56f669c.png)

[stochastic_cross.xml.zip](https://github.com/binary-ex-machina/binary.com-bot/files/1744417/stochastic_cross.xml.zip)

**Comment by janps1712** [comment]
Thank you very much
