### ISSUE TITLE
Bot lucrativo

### ISSUE THREAD

**Issue by jonas-sp** [binary-ex-machina/binary.com-bot#90]
Machina, eu vi que vc é Brasileiro também, vou escrever em Português. 
   Estou conseguindo dinheiro com uma estratégia para um contrato de dígitos, Over e Under. Mas quero fazer um Bot para a estratégia para automatizar, pois estou fazendo manualmente!  
   Preciso conseguir analisar os últimos 25 dígitos,  e a porcentagem que 3 deles saíram na ultima sequência, se  a porcentagem dos 3 estiver baixa, entrar com a compra do contrato.  Pode me ajudar, por favor?? o cálculo da porcentagem está pegando para mim, eu vi alguns scripts aqui no Github, mas de apenas um digito e não para comparação de 3 e para estratégias de Differs, não é o caso aqui!  posso explicar melhor se me contatar, obrigado!!!!

**Comment by binary-ex-machina** [comment]
opa, o que você ta querendo fazer é complexo e talvez o que vou mandar aqui não funcione como você precisa, mas acho que já é um começo. Usei o script do FruitFella https://gist.githubusercontent.com/Fruitfella/ab019eedc64c2c525adfcc9900b99413/raw/abd0050418294f21e90e3993f6a1e47a316681f3/FRUITFELLA's_LD_Analyzer_ver.2.0.xml

A ideia é pegar a % de cada digito, colocar eles em uma lista. Depois analisar cada item da lista e conferir se ele é o menor numero daquela lista, remover aquele elemento e repetir com a analise. Na imagem abaixo vai seguir a ideia de  que se os digitos 0,1 e 2 forem os com menor % nos ultimos 25 digitos, ele compra Over com prediction 3. Fiz uns testes aqui e não foram bons

![image](https://user-images.githubusercontent.com/34610787/72228974-0393d380-358a-11ea-8ff2-a657b6d4fb4d.png)

**Comment by jonas-sp** [comment]
A ideia é que se, por exemplo(considerando lista dos últimos 25): quantidade de números 0 menor que 8% E quantidade de número 1 menor que 8% E quantidade de número 2 menor que 8% comprar over. E também usar prediction 2 e não 3, como usou, mas estava indo bem!! Será que é possível?

**Comment by binary-ex-machina** [comment]
Sim
![image](https://user-images.githubusercontent.com/34610787/72231046-de0dc680-3597-11ea-9915-4431a4251364.png)

**Comment by jonas-sp** [comment]
Pode enviar o xml por favor? Pra eu ver?
