### ISSUE TITLE
Kindly assist in refining this strategy

### ISSUE THREAD

**Issue by mathengem** [binary-ex-machina/binary.com-bot#93]
Have this strategy for last digit over that is working well but sometimes the losses are a bit too much much wanted to have an option where if the number after the tick is not over and its the same it skips buying the contract until the number after the tick is more than the last digit.
[LastDigit1-Strategy-Botxml.txt](https://github.com/binary-ex-machina/binary.com-bot/files/8945484/LastDigit1-Strategy-Botxml.txt)

**Comment by binary-ex-machina** [comment]
The strategy is way complex and I can't understand what you want to do. Try to create a variable that stores the number of sequential losses and then compare that variable with the number you want. Inside that IF block, you do what you want.
