### ISSUE TITLE
Binary bot strategy : would be best strategy of the year 

### ISSUE THREAD

**Issue by promzy4844** [binary-ex-machina/binary.com-bot#94]
Please help me 
I have this strategy of hand but I can't code it.
This is it:
 Let binary bot compare different spots , and if bot finds two different spots  with the same last digit ,bot should trade digit differ:
Eg first spot=xxx.10
Second Spot=xxx.11
Third spots=xxx.22
Fourth spot=xxx.30
Solution: the first and the fourth spot has the same last digit which is 0
Therefore  bot should purchase digit differ 0.
@binary-ex-machina please help me

**Comment by binary-ex-machina** [comment]
@promzy4844, you have two options, working with a fixed prediction or a dynamic prediction.

The dynamic prediction will analyze any digit the same as one of the last digits, as you can choose the spot they are. The example below will compare the latest and the 4th from the previous digits. The main problem with this approach is that it will take one tick to make the trade, so it will have one tick delay to start trading.

[dynamic.json.zip](https://github.com/binary-ex-machina/binary.com-bot/files/11171752/dynamic.json.zip)

![image](https://user-images.githubusercontent.com/34610787/230415220-06c915f8-bbe4-496c-8918-1291bc4adc32.png)

The fixed prediction will work. Differently, it will not have a delay, but it will function with just one prediction.

[fixed.json.zip](https://github.com/binary-ex-machina/binary.com-bot/files/11171802/fixed.json.zip)

![image](https://user-images.githubusercontent.com/34610787/230416469-96bd9c42-8851-4213-91cc-46bbc1112a1c.png)
